name = "yhautopartschina-website"
compatibility_date = "2025-07-01"

[[d1_databases]]
binding = "DB"
database_name = "global-luxe-db"
database_id = ""

[env.production]
d1_databases = [
  { binding = "DB", database_name = "global-luxe-db", database_id = "" }
]
